# -*- coding: utf-8 -*-
"""EYE_XAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gOnZmv_5KtFbUmnJjC574y8W0ZmCVGXn
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
!pip install imagehash
import imagehash
from collections import defaultdict
from PIL import Image
from sklearn.utils import resample
from sklearn.preprocessing import LabelEncoder
import pickle
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.applications import ResNet101V2, DenseNet121, InceptionV3
from tensorflow.keras import layers, models
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report, accuracy_score
!pip install lime
from lime import lime_image
from skimage.segmentation import mark_boundaries
from tensorflow.keras.preprocessing import image
from scipy.stats import mode
from xgboost import XGBClassifier
import cv2
from google.colab import drive
!pip install shap -q
import shap

"""## DATA SET

https://www.kaggle.com/datasets/amrsalemhelmy/ocular-disease/data
"""

# Path to your dataset
import zipfile

zip_path = '/content/drive/MyDrive/DATASET/archive.zip'
extract_path = '/content/dataset/'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Done! Extracted files:")
import os
for folder in os.listdir(extract_path):
    print(f" - {folder}")

# List to store image paths and labels
data = []
dataset_path = '/content/dataset/dataset/dataset/'

# Walk through each subdirectory
for label in os.listdir(dataset_path):
    label_folder = os.path.join(dataset_path, label)
    if os.path.isdir(label_folder):
        for file in os.listdir(label_folder):
            file_path = os.path.join(label_folder, file)
            if file.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.tif', '.tiff')):
                data.append({"image": file_path, "label": label})

df = pd.DataFrame(data)

df.info()

df.head()

"""## EDA"""

# Check how many unique classes
num_classes = df['label'].nunique()
print(f"Number of unique classes: {num_classes}")

df['label'].unique()

# Count number of images per class
class_counts = df['label'].value_counts()
print("Number of images per class: ")
print(class_counts)

# Plotting
plt.figure(figsize=(12, 6))
sns.barplot(x=class_counts.index, y=class_counts.values, palette="viridis")
plt.title("Number of Images per Class")
plt.xlabel("Class (Label)")
plt.ylabel("Number of Images")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

# Set number of classes and samples per class to display
n_classes = min(5, df['label'].nunique())
samples_per_class = 3

unique_labels = df['label'].unique()

plt.figure(figsize=(samples_per_class * 3, n_classes * 3))

for i, label in enumerate(unique_labels[:n_classes]):
    label_df = df[df['label'] == label]
    samples = label_df.sample(n=min(samples_per_class, len(label_df)))

    for j, (_, row) in enumerate(samples.iterrows()):
        img = Image.open(row['image']).convert('RGB')
        plt.subplot(n_classes, samples_per_class, i * samples_per_class + j + 1)
        plt.imshow(img)
        plt.title(label)
        plt.axis('off')

plt.tight_layout()
plt.show()

# Get dimensions of each image
def get_image_shape(path):
    with Image.open(path) as img:
        return img.size  # returns (width, height)

df['dimensions'] = df['image'].apply(get_image_shape)
df['width'] = df['dimensions'].apply(lambda x: x[0])
df['height'] = df['dimensions'].apply(lambda x: x[1])

# Basic stats
print(df[['width', 'height']].describe())

plt.figure(figsize=(12, 5))
sns.histplot(df['width'], bins=30, color='skyblue', label='Width')
sns.histplot(df['height'], bins=30, color='salmon', label='Height')
plt.legend()
plt.title('Distribution of Image Width and Height')
plt.xlabel('Pixels')
plt.ylabel('Frequency')
plt.show()

df['aspect_ratio'] = df['width'] / df['height']

plt.figure(figsize=(10, 4))
sns.histplot(df['aspect_ratio'], bins=30, kde=True)
plt.title('Distribution of Image Aspect Ratios')
plt.xlabel('Aspect Ratio (Width / Height)')
plt.ylabel('Frequency')
plt.show()

def compute_brightness(img_path):
    img = Image.open(img_path).convert('L')  # convert to grayscale
    stat = img.getdata()
    return sum(stat) / len(stat)

df['brightness'] = df['image'].apply(compute_brightness)

plt.figure(figsize=(10, 4))
sns.histplot(df['brightness'], bins=30, color='goldenrod', kde=True)
plt.title('Distribution of Image Brightness')
plt.xlabel('Brightness (0=Dark, 255=Bright)')
plt.ylabel('Frequency')
plt.show()

def plot_rgb_histogram(img_path):
    img = Image.open(img_path).convert('RGB')
    r, g, b = img.split()

    plt.figure(figsize=(10, 3))
    plt.hist(r.getdata(), bins=256, color='red', alpha=0.5, label='Red')
    plt.hist(g.getdata(), bins=256, color='green', alpha=0.5, label='Green')
    plt.hist(b.getdata(), bins=256, color='blue', alpha=0.5, label='Blue')
    plt.title(f'RGB Histogram: {os.path.basename(img_path)}')
    plt.xlabel('Pixel Value')
    plt.ylabel('Frequency')
    plt.legend()
    plt.tight_layout()
    plt.show()

# Show for 3 random images
for path in df.sample(5)['image']:
    plot_rgb_histogram(path)

# Compute hash for each image
df['hash'] = df['image'].apply(lambda x: str(imagehash.average_hash(Image.open(x).convert('RGB'))))

# Count duplicates
hash_groups = df.groupby('hash')['image'].apply(list)
duplicates = hash_groups[hash_groups.apply(len) > 1]

print(f"Number of duplicate hash groups: {len(duplicates)}")
print("Sample duplicate group:")
# Display a sample duplicate group
for i, paths in enumerate(duplicates.head(1)):
    for path in paths:
        img = Image.open(path)
        plt.imshow(img)
        plt.title(os.path.basename(path))
        plt.axis('off')
        plt.show()

TARGET_SAMPLES = 1000

balanced_df = pd.concat([
    resample(df[df['label'] == label],
             replace=True if len(df[df['label'] == label]) < TARGET_SAMPLES else False,
             n_samples=TARGET_SAMPLES,
             random_state=42)
    for label in df['label'].unique()
])

balanced_df = balanced_df.sample(frac=1, random_state=42).reset_index(drop=True)

print(balanced_df['label'].value_counts())

"""## Encoding the labels"""

label_encoder = LabelEncoder()
balanced_df['encoded_label'] = label_encoder.fit_transform(balanced_df['label'])

with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(label_encoder, f)

label_names = label_encoder.classes_

"""## Preprocessing"""

# Parameters
IMG_SIZE = (512, 512)
BATCH_SIZE = 32

# Image preprocessing function
def process_path(file_path, label):
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, IMG_SIZE)
    img = img / 255.0  # Normalize to [0, 1]
    return img, label

"""## Data Spliting"""

train_df, val_df = train_test_split(
    balanced_df,
    test_size=0.2,
    stratify=balanced_df['encoded_label'],
    random_state=42
)

train_paths = train_df['image'].values
train_labels = train_df['encoded_label'].values

val_paths = val_df['image'].values
val_labels = val_df['encoded_label'].values

"""##### optimize the datas to fit GPU memory"""

train_ds = tf.data.Dataset.from_tensor_slices((train_paths, train_labels))
val_ds = tf.data.Dataset.from_tensor_slices((val_paths, val_labels))

train_ds = train_ds.map(process_path, num_parallel_calls=tf.data.AUTOTUNE)
val_ds = val_ds.map(process_path, num_parallel_calls=tf.data.AUTOTUNE)

train_ds = train_ds.shuffle(buffer_size=1000).batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
val_ds = val_ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

NUM_CLASSES = balanced_df['encoded_label'].nunique()
EPOCHS = 100
N = 30

"""# MODEL WEIGHTS LOADING"""

import tf_keras
import pickle

model_resnet   = tf_keras.models.load_model('/content/drive/MyDrive/MODELS/ResNet101V2.keras', compile=False)
model_incv3    = tf_keras.models.load_model('/content/drive/MyDrive/MODELS/InceptionV3.keras', compile=False)
model_dense    = tf_keras.models.load_model('/content/drive/MyDrive/MODELS/DenseNet_121.keras', compile=False)

print("All models loaded successfully!")

"""# TRAINING

## ResNet101V2 Model Architecture
"""

# Load base model
base_model_resnest = ResNet101V2(weights='imagenet', include_top=False, input_shape=(512, 512, 3))

# Unfreeze the last N layers of ResNet101V2
base_model_resnest.trainable = True

# Freeze all layers except the last N
for layer in base_model_resnest.layers[:-N]:
    layer.trainable = False

# Freeze BatchNorm layers even in the last N
for layer in base_model_resnest.layers:
    if isinstance(layer, tf.keras.layers.BatchNormalization):
        layer.trainable = False

# Add custom head
model_resnest = models.Sequential([
    base_model_resnest,
    layers.GlobalAveragePooling2D(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(NUM_CLASSES, activation='softmax')
])

model_resnest.summary()

"""## InceptionV3 Model Architecture"""

base_model_InceptionV3 = InceptionV3(weights='imagenet', include_top=False, input_shape=(512, 512, 3))

# Unfreeze the last N layers of InceptionV3
base_model_InceptionV3.trainable = True

# Freeze all layers except the last N
for layer in base_model_InceptionV3.layers[:-N]:
    layer.trainable = False

# Freeze BatchNorm layers even in the last N
for layer in base_model_InceptionV3.layers:
    if isinstance(layer, tf.keras.layers.BatchNormalization):
        layer.trainable = False

# Add custom head
model_InceptionV3 = models.Sequential([
    base_model_InceptionV3,
    layers.GlobalAveragePooling2D(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(NUM_CLASSES, activation='softmax')
])

model_InceptionV3.summary()

"""## DenseNet121 Model Architecture"""

base_model_densenet = DenseNet121(weights='imagenet', include_top=False, input_shape=(512, 512, 3))

# Unfreeze the last N layers of DenseNet121
base_model_densenet.trainable = True

# Freeze all layers except the last N
for layer in base_model_densenet.layers[:-N]:
    layer.trainable = False

# Freeze BatchNorm layers even in the last N
for layer in base_model_densenet.layers:
    if isinstance(layer, tf.keras.layers.BatchNormalization):
        layer.trainable = False

# Add custom head
model_densenet = models.Sequential([
    base_model_densenet,
    layers.GlobalAveragePooling2D(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(NUM_CLASSES, activation='softmax')
])

model_densenet.summary()

"""## Callbacks"""

# Reduce LR if validation accuracy stops improving
lr_callback = ReduceLROnPlateau(
    monitor='val_accuracy',
    factor=0.5,        # reduce LR by half
    patience=4,        # wait for 4 epochs of no improvement
    verbose=2,
    min_lr=1e-6
)

# EarlyStopping callback to stop training when validation loss stops improving
early_stopping = EarlyStopping(monitor='val_loss',
                               patience=8,
                               verbose=2,
                               restore_best_weights=True)

"""## Training ResNet101V2, InceptionV3 and DenseNet121"""

# Train all three models
models_histories = {}

# Helper function to build and train models
def build_and_train_model(model, name):
    model.compile(optimizer=tfa.optimizers.AdamW(weight_decay=1e-4, learning_rate=1e-5), loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    history = model.fit(train_ds, validation_data=val_ds, epochs=EPOCHS, callbacks=[lr_callback, early_stopping])
    return model, history

model_resnet, hist_resnet = build_and_train_model(model_resnest, 'ResNet101V2')
models_histories['ResNet101'] = (model_resnet, hist_resnet)

model_incv3, hist_incv3 = build_and_train_model(model_InceptionV3, 'InceptionV3')
models_histories['InceptionV3'] = (model_incv3, hist_incv3)

model_dense, hist_densenet = build_and_train_model(model_densenet, 'DenseNet121')
models_histories['DenseNet121'] = (model_dense, hist_densenet)

"""# METRICS"""

def plot_metric(histories, metric, title, ylabel):
    plt.figure(figsize=(10, 6))
    for name, (_, history) in histories.items():
        plt.plot(history.history[metric], label=f'{name} {metric}', linewidth=2)
    plt.title(title)
    plt.xlabel('Epoch')
    plt.ylabel(ylabel)
    plt.legend()
    plt.grid(True)
    plt.show()

# Plot Training Accuracy
plot_metric(models_histories, 'accuracy', 'Training Accuracy Comparison', 'Accuracy')

# Plot Validation Accuracy
plot_metric(models_histories, 'val_accuracy', 'Validation Accuracy Comparison', 'Accuracy')

# Plot Training Loss
plot_metric(models_histories, 'loss', 'Training Loss Comparison', 'Loss')

# Plot Validation Loss
plot_metric(models_histories, 'val_loss', 'Validation Loss Comparison', 'Loss')

# Evaluate and plot confusion matrices
def evaluate_and_plot_cm(model, name):
    y_true, y_pred = [], []

    for images, labels in val_ds:
        preds = model.predict(images)
        y_true.extend(labels.numpy())
        y_pred.extend(np.argmax(preds, axis=1))

    cm = confusion_matrix(y_true, y_pred)
    print(f"Classification Report for {name}:\n", classification_report(y_true, y_pred, target_names=label_names))

    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=label_names)
    plt.figure(figsize=(8, 6))
    disp.plot(cmap='Blues', xticks_rotation=45)
    plt.title(f'Confusion Matrix - {name}')
    plt.show()

for name, (model, _) in models_histories.items():
    evaluate_and_plot_cm(model, name)

"""## Saving the models"""

model_resnet.save("ResNet101V2.keras")
model_incv3.save("InceptionV3.keras")
model_dense.save("DenseNet_121.keras")

"""## Implementation of XAI"""

img_path = '/content/dataset/dataset/dataset/ARMD/0_ORID19_160_ARMD.png'
img = tf.keras.preprocessing.image.load_img(img_path, target_size=(512, 512))
img_array = tf.keras.preprocessing.image.img_to_array(img)
img_array = np.expand_dims(img_array / 255.0, axis=0)

"""## GradCam"""

def make_gradcam_heatmap(img_array, full_model, conv_layer_name, pred_index=None):
    import tf_keras
    import numpy as np

    base_model = full_model.layers[0]
    conv_layer = base_model.get_layer(conv_layer_name)

    # Build grad model using ONLY tf_keras
    grad_model = tf_keras.Model(
        inputs=base_model.input,
        outputs=[conv_layer.output, base_model.output]
    )

    img_tensor = tf.constant(img_array, dtype=tf.float32)

    with tf.GradientTape() as tape:
        tape.watch(img_tensor)
        conv_outputs, base_out = grad_model(img_tensor, training=False)
        tape.watch(conv_outputs)

        # Manually run the head layers (after base_model)
        x = conv_outputs
        # Actually run full prediction using base_out through head
        head_input = base_out
        for layer in full_model.layers[1:]:  # GAP, Dense, Dropout, Dense
            head_input = layer(head_input, training=False)
        predictions = head_input

        if pred_index is None:
            pred_index = int(tf.argmax(predictions[0]))
        class_channel = predictions[:, pred_index]

    grads = tape.gradient(class_channel, conv_outputs)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
    heatmap = conv_outputs[0] @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)
    heatmap = tf.maximum(heatmap, 0) / (tf.math.reduce_max(heatmap) + 1e-8)

    return heatmap.numpy()

cam_model = model_resnet
conv_layer_name = 'conv4_block23_out'

heatmap = make_gradcam_heatmap(img_array, cam_model, conv_layer_name)

plt.imshow(tf.keras.preprocessing.image.array_to_img(img_array[0]))
plt.imshow(heatmap, cmap='jet', alpha=0.4)
plt.title("Grad-CAM Heatmap")
plt.axis('off')
plt.show()

heatmap_resized = cv2.resize(heatmap, (512, 512), interpolation=cv2.INTER_CUBIC)
heatmap_colored = cv2.applyColorMap(np.uint8(255 * heatmap_resized), cv2.COLORMAP_JET)
heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)
original_img = (img_array[0] * 255).astype(np.uint8)
superimposed_img = cv2.addWeighted(original_img, 0.6, heatmap_colored, 0.4, 0)

plt.figure(figsize=(8, 8))
plt.imshow(superimposed_img)
plt.axis('off')
plt.title("Grad-CAM Heatmap Overlay")
plt.show()

"""## Lime Image Explainer"""

def preprocess_image(img_path, target_size=(512, 512)):
    img = image.load_img(img_path, target_size=target_size)
    img_array = image.img_to_array(img)
    return img_array.astype(np.uint8), np.expand_dims(img_array / 255.0, axis=0)

def predict_fn(images):
    images = np.array(images) / 255.0
    return model_resnet.predict(images)

original_img, input_img = preprocess_image(img_path)

explainer = lime_image.LimeImageExplainer()

explanation = explainer.explain_instance(
    image=original_img,
    classifier_fn=predict_fn,
    top_labels=1,
    hide_color=0,
    num_samples=1000
)

temp, mask = explanation.get_image_and_mask(
    label=explanation.top_labels[0],
    positive_only=True,
    num_features=10,
    hide_rest=False
)
plt.imshow(mark_boundaries(temp / 255.0, mask))
plt.title("LIME Explanation - Outlined Superpixels")
plt.axis('off')
plt.show()

temp, mask = explanation.get_image_and_mask(
    label=explanation.top_labels[0],
    positive_only=True,
    num_features=10,
    hide_rest=True
)
plt.imshow(temp)
plt.title("LIME Explanation - Highlighted Superpixels Only")
plt.axis('off')
plt.show()

temp, mask = explanation.get_image_and_mask(
    label=explanation.top_labels[0],
    positive_only=False,
    num_features=15,
    hide_rest=False
)
plt.imshow(mark_boundaries(temp / 255.0, mask))
plt.title("LIME Explanation - Positive and Negative Contributions")
plt.axis('off')
plt.show()

def lime_explain_and_plot(model, img_path, target_size=(512, 512),
                          positive_only=False, num_features=15, hide_rest=False,
                          num_samples=1000):

    def preprocess_image(img_path, target_size=target_size):
        img = image.load_img(img_path, target_size=target_size)
        img_array = image.img_to_array(img)
        return img_array.astype(np.uint8), np.expand_dims(img_array / 255.0, axis=0)

    def predict_fn(images):
        images = np.array(images) / 255.0
        return model.predict(images)

    original_img, input_img = preprocess_image(img_path)

    explainer = lime_image.LimeImageExplainer()
    explanation = explainer.explain_instance(
        image=original_img,
        classifier_fn=predict_fn,
        top_labels=1,
        hide_color=0,
        num_samples=num_samples
    )

    temp, mask = explanation.get_image_and_mask(
        label=explanation.top_labels[0],
        positive_only=positive_only,
        num_features=num_features,
        hide_rest=hide_rest
    )

    plt.figure(figsize=(8, 8))
    plt.imshow(mark_boundaries(temp / 255.0, mask))
    plt.title(f"LIME Explanation\nPositive Only: {positive_only}, Num Features: {num_features}, Hide Rest: {hide_rest}")
    plt.axis('off')
    plt.show()

lime_explain_and_plot(model_incv3, img_path, positive_only=False, num_features=15, hide_rest=False)

lime_explain_and_plot(model_incv3, img_path, positive_only=True, num_features=15, hide_rest=True)

lime_explain_and_plot(model_resnet, img_path, positive_only=False, num_features=15, hide_rest=False)

lime_explain_and_plot(model_resnet, img_path, positive_only=True, num_features=15, hide_rest=True)

lime_explain_and_plot(model_dense, img_path, positive_only=False, num_features=15, hide_rest=False)

lime_explain_and_plot(model_dense, img_path, positive_only=True, num_features=15, hide_rest=True)

"""---

---

# SHAP
"""

def shap_explain(model, img_path, val_ds, label_names,
                 num_background=5, target_size=(256, 256), nsamples=25):

    # ---------------------------
    # 1. Load image (256x256)
    # ---------------------------
    img = tf.keras.preprocessing.image.load_img(img_path, target_size=target_size)
    img_array = tf.keras.preprocessing.image.img_to_array(img) / 255.0
    img_input = np.expand_dims(img_array, axis=0)

    # ---------------------------
    # 2. Get predicted class (using 512)
    # ---------------------------
    preds = model.predict(tf.image.resize(img_input, (512, 512)), verbose=0)
    pred_class = int(np.argmax(preds))

    # ---------------------------
    # 3. Prepare background (IMPORTANT: resize to 256)
    # ---------------------------
    background = []
    for images, _ in val_ds.take(2):
        for img in images:
            img_resized = tf.image.resize(img, target_size)
            background.append(img_resized.numpy())

            if len(background) >= num_background:
                break
        if len(background) >= num_background:
            break

    background = np.array(background[:num_background])

    # ---------------------------
    # 4. Flatten for SHAP
    # ---------------------------
    bg_flat = background.reshape(num_background, -1)
    img_flat = img_input.reshape(1, -1)

    # ---------------------------
    # 5. Prediction function
    # ---------------------------
    def predict_fn(x_flat):
        x = x_flat.reshape(-1, target_size[0], target_size[1], 3)
        x_resized = tf.image.resize(x, (512, 512))

        preds = model.predict(x_resized, verbose=0)

        # ensure 2D
        if len(preds.shape) == 1:
            preds = np.expand_dims(preds, axis=0)

        return preds[:, pred_class].reshape(-1)

    # ---------------------------
    # 6. SHAP explainer
    # ---------------------------
    explainer = shap.KernelExplainer(predict_fn, bg_flat)
    shap_values = explainer.shap_values(img_flat, nsamples=nsamples)

    # ---------------------------
    # 7. Reshape for visualization
    # ---------------------------
    shap_img = shap_values.reshape(1, target_size[0], target_size[1], 3)
    img_show = img_input.reshape(1, target_size[0], target_size[1], 3)

    # ---------------------------
    # 8. Plot
    # ---------------------------
    print(f"Predicted class: {label_names[pred_class]}")
    shap.image_plot(shap_img, img_show, labels=[label_names[pred_class]])

    return shap_values, pred_class

shap_values, pred_class = shap_explain(
    model_incv3,
    img_path,
    val_ds,
    label_names,
    num_background=5,
    target_size=(256, 256),
    nsamples=25
)

"""AS WE CAN SEE DUE TO THE  SHEER AMOUNT OF FEATURES SHAP ISN'T WORKING QUITE WELL, THAT'S THE REASON GradCAM IS USED IN MEDICAL IMAGES OR IMAGES WITH HIGH RES/LOT OF SUPER-PIXELS"""











































































































































































